[package]
name = "rlget"
version = "0.0.1"
edition = "2024"
authors = ["jake@mccoy.engineer", "songrun"]

[dependencies]
reqwest = "0.9.3"
docopt = "1.1.0"
serde = "1.0.91"
indicatif = "0.12.0"
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
